-- MySQL Script generated by MySQL Workbench
-- Tue Aug 13 14:54:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nbgs_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nbgs_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nbgs_db` DEFAULT CHARACTER SET utf8 ;
USE `nbgs_db` ;

-- -----------------------------------------------------
-- Table `nbgs_db`.`dogadaji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nbgs_db`.`dogadaji` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(100) NOT NULL,
  `mjesto` VARCHAR(100) NOT NULL,
  `datum` DATE NOT NULL,
  `organizator` VARCHAR(100) NOT NULL,
  `kratki_opis` VARCHAR(200) NOT NULL,
  `korisnik_veza` VARCHAR(256),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

INSERT INTO `dogadaji` (`id`,`naziv`,`mjesto`,`datum`,`organizator`,`kratki_opis`,`korisnik_veza`) 
  VALUES (1,'Star Wars Armada','Čakovec','2019-10-11','Jura Cilar','U 16:00','jcilar6@gmail.com');
INSERT INTO `dogadaji` (`id`,`naziv`,`mjesto`,`datum`,`organizator`,`kratki_opis`,`korisnik_veza`) 
  VALUES (2,'XCOM The Board Game','Casa Latina','2019-10-22','Matteo Posavec','U 19:30','jura.cilar@student.mev');
  
commit;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
