// <auto-generated />
namespace Board_Game_Stranica_N_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ime));
        
        string IMigrationMetadata.Id
        {
            get { return "201908211323594_ime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
